# pool:
#   vmImage: Ubuntu 16.04

jobs:
  - job: job1
    pool:
      vmImage: Ubuntu 16.04
    steps:
      - script: echo 1

  - job: job2
    pool:
      vmImage: Ubuntu 16.04
    steps:
      - script: echo 2

  - job: job3
    pool:
      vmImage: Ubuntu 16.04
    steps:
      - script: echo 3
