name: $(SourceBranchName)-$(Rev:.r)
container: pipehub/ci:1

# variables:
#   EXEC_CONTAINER: false

trigger:
  batch: true
  paths:
    exclude:
      - cmd/pipehub/pipehub.sample.hcl
      - misc/docker/build/entrypoint.sh
      - misc/docker/ci/tools.json
      - .gitignore
      - .goreleaser.yml
      - changelog.md
      - license
      - readme.md

jobs:
  - job: job1
    pool:
      vmImage: Ubuntu 16.04
    steps:
      - script: echo 1

  - job: job2
    pool:
      vmImage: Ubuntu 16.04
    steps:
      - script: echo 2

  - job: job3
    pool:
      vmImage: Ubuntu 16.04
    steps:
      - script: echo 3
