name: $(SourceBranchName)-$(Rev:.r)

variables:
  EXEC_CONTAINER: false

trigger:
  batch: true
  paths:
    exclude:
      - cmd/pipehub/pipehub.sample.hcl
      - misc/docker/build/entrypoint.sh
      - misc/docker/ci/tools.json
      - .gitignore
      - .goreleaser.yml
      - changelog.md
      - license
      - readme.md

jobs:
  - template: jobs/build.yml
    parameters:
      name: quality_go_test
      container: pipehub/ci:1
      displayName: Quality | Go Test
      command: make go-test

  # - job: quality_go_test
  #   container: pipehub/ci:1
  #   pool:
  #     vmImage: Ubuntu 16.04
  #   displayName: Quality | Go Test
  #   steps:
  #     - script: make go-test

  - job: quality_go_linter
    container: pipehub/ci:1
    pool:
      vmImage: Ubuntu 16.04
    displayName: Quality | Go Linter
    steps:
      - script: make go-linter

  - job: quality_go_linter_vendor
    container: pipehub/ci:1
    pool:
      vmImage: Ubuntu 16.04
    displayName: Quality | Go Linter Vendor
    steps:
      - script: make go-linter-vendor

  - job: quality_docker_linter
    container: pipehub/ci:1
    pool:
      vmImage: Ubuntu 16.04
    displayName: Quality | Docker Linter
    steps:
      - script: make docker-linter

  - job: build_go
    container: pipehub/ci:1
    pool:
      vmImage: Ubuntu 16.04
    displayName: Build | Go
    steps:
      - script: go build -mod readonly -o bin/pipehub/pipehub cmd/pipehub/*.go
