pool:
  vmImage: Ubuntu 16.04

name: $(SourceBranchName)-$(Rev:.r)
container: pipehub/ci:1

jobs:
  - job: Windows
    steps:
      - script: echo hello from Windows

  - job: macOS
    steps:
      - script: echo hello from macOS

  - job: Linux
    steps:
      - script: echo hello from Linux
