pool:
  vmImage: Ubuntu 16.04

name: $(SourceBranchName)-$(Rev:.r)
container: pipehub/ci:1

variables:
  EXEC_CONTAINER: false

trigger:
  batch: true
  paths:
    exclude:
      - cmd/pipehub/pipehub.sample.hcl
      - misc/docker/build/entrypoint.sh
      - misc/docker/ci/tools.json
      - .gitignore
      - .goreleaser.yml
      - changelog.md
      - license
      - readme.md

stages:
  - stage: Quality
    displayName: Quality stage
    jobs:
      - job: Go
        steps:
          - script: |
              go build -mod readonly -o bin/pipehub/pipehub cmd/pipehub/*.go
            displayName: 'Build'

          - script: |
              make go-test
            displayName: 'Test'

          - script: |
              make go-linter
            displayName: 'Linter'

          - script: |
              make go-linter-vendor
            displayName: 'Linter Vendor'

      - Job: Docker
        steps:
          - script: |
              make docker-linter
            displayName: 'Linter'
# steps:
#   - job: Quality
#     steps:
#       - script: |
#           go build -mod readonly -o bin/pipehub/pipehub cmd/pipehub/*.go
#         displayName: 'Build'

#       - script: |
#           make go-test
#         displayName: 'Quality - Go Test'

#       - script: |
#           make go-linter
#         displayName: 'Quality - Go Linter'

#       - script: |
#           make go-linter-vendor
#         displayName: 'Quality - Go Linter Vendor'

#       - script: |
#           make docker-linter
#         displayName: 'Quality - Docker Linter'

#   - job: Build
#     dependsOn: Build
#     steps:
#       - script: |
#           make build
